package com.project.hibernate.entity.User;

import java.util.ArrayList;
import java.util.List;

public class Departmen {
    public List returnSubdivision(){
        List<String> subChoices = new ArrayList<String>();
        subChoices.add("Административно-технический отдел");
        subChoices.add("Администрация Ай ФОРС");
        subChoices.add("Аналитически отдел");
        subChoices.add("Аппарат Генерального директора");
        subChoices.add("Бухгалтерия");
        subChoices.add("Группа по сопровождению  и контролю инвестиционных проектов");
        subChoices.add("Департамент автоматизации Федерального Казначейства");
        subChoices.add("Департамент банковских технологий");
        subChoices.add("Департамент информационных технологий для банков");
        subChoices.add("Департамент по работе с Госсектором");
        subChoices.add("Департамент продаж и развития сервисных продуктов");
        subChoices.add("Департамент развития комплексных проектов");
        subChoices.add("Департамент системной интеграции");
        subChoices.add("Директорат");
        subChoices.add("Директорат ФОРС Дистрибуция");
        subChoices.add("Курьерская служба");
        subChoices.add("Лаборатория решений");
        subChoices.add("Лаборатория решений ФОРС");
        subChoices.add("Отдел административного обеспечения");
        subChoices.add("Отдел бизнес анализа Ай - ФОРС");
        subChoices.add("Отдел веб-дизайна Ай – ФОРС");
        subChoices.add("Отдел внедрения АСУП");
        subChoices.add("Отдел исследовательских проектов");
        subChoices.add("Отдел логистики");
        subChoices.add("Отдел маркетинга");
        subChoices.add("Отдел маркетинга Ай – ФОРС");
        subChoices.add("Отдел маркетинга и развития бизнеса");
        subChoices.add("Отдел образовательных программ");
        subChoices.add("Отдел организационного обеспечения");
        subChoices.add("Отдел по работе с клиентами Ай – ФОРС");
        subChoices.add("Отдел по работе с персоналом");
        subChoices.add("Отдел по развитию бизнеса Ай – ФОРС");
        subChoices.add("Отдел по развитию международного бизнеса");
        subChoices.add("Отдел правового сопровождения");
        subChoices.add("Отдел продаж коммерческого департамента");
        subChoices.add("Отдел разработки");
        subChoices.add("Отдел разработки Ай – ФОРС");
        subChoices.add("Отдел разработки государственных проектов");
        subChoices.add("Отдел решений информационной безопасности");
        subChoices.add("Отдел системного анализа и проектирования Ай  - ФОРС");
        subChoices.add("Отдел тестирования");
        subChoices.add("Отдел тестирования Ай – ФОРС");
        subChoices.add("Отдел технического обеспечения ЦТП");
        subChoices.add("Отдел технологии Больших Данных Ай – ФОРС");
        subChoices.add("Отделение ERP-систем Центра технической поддержки");
        subChoices.add("Отделение автоматизации деловых процессов");
        subChoices.add("Отделение административного обеспечения");
        subChoices.add("Отделение аналитических технологий");
        subChoices.add("Отделение бизнес-консалтинга");
        subChoices.add("Отделение ИТ консалтинга");
        subChoices.add("Отделение карточных технологий");
        subChoices.add("Отделение комплексного проектирования информационных систем");
        subChoices.add("Отделение корпоративных интернет решений");
        subChoices.add("Отделение маркетинга и развития бизнеса Ай-ФОРС");
        subChoices.add("Отделение по продвижению продуктов и решений Ай-ФОРС");
        subChoices.add("Отделение продуктовых решений");
        subChoices.add("Отделение профессиональных сервисов");
        subChoices.add("Отделение разработки информационных систем");
        subChoices.add("Отделение телекоммуникационных систем");
        subChoices.add("Отделение технологического консалтинга");
        subChoices.add("Отделение технологического консалтинга Дистрибуция");
        subChoices.add("Отделение финансово-аналитических технологий");
        subChoices.add("Проектный офис");
        subChoices.add("Секретариат");
        subChoices.add("Служба внедрения и сопровождения");
        subChoices.add("Служба системных администраторов");
        subChoices.add("Служба управления персоналом");
        subChoices.add("Финансово-плановый отдел");
        subChoices.add("Финансовый департамент");
        subChoices.add("Финансовый отдел");
        subChoices.add("ФОРС Дистрибуция");
        subChoices.add("Центр техподдержки");
        subChoices.add("Юридический департамент");
        subChoices.add("Юридический департамент Дистрибуция");

        return subChoices;
    }

    public List returnPosition(){
        List<String> subChoicesPosition = new ArrayList<String>();
        subChoicesPosition.add("PR-менеджер");
        subChoicesPosition.add("Web-разработчик");
        subChoicesPosition.add("Администратор");
        subChoicesPosition.add("Администратор офиса");
        subChoicesPosition.add("Администратор проектов");
        subChoicesPosition.add("Аналитик");
        subChoicesPosition.add("Архитектор проектов");
        subChoicesPosition.add("Ассистент менеджера");
        subChoicesPosition.add("Аудитор");
        subChoicesPosition.add("Бизнес-аналитик");
        subChoicesPosition.add("Бухгалтер");
        subChoicesPosition.add("Веб-дизайнер");
        subChoicesPosition.add("Ведущий эксперт");
        subChoicesPosition.add("Ведущий IOS-программист");
        subChoicesPosition.add("Ведущий аналитик");
        subChoicesPosition.add("Ведущий аналитик 1 категории");
        subChoicesPosition.add("Ведущий аналитик 2 категории");
        subChoicesPosition.add("Ведущий аналитик 3 категории");
        subChoicesPosition.add("Ведущий Андроид программист");
        subChoicesPosition.add("Ведущий архитектор проектов");
        subChoicesPosition.add("Ведущий бизнес аналитик");
        subChoicesPosition.add("Ведущий инженер");
        subChoicesPosition.add("Ведущий инженер 1 категории");
        subChoicesPosition.add("Ведущий консультант");
        subChoicesPosition.add("Ведущий менеджер");
        subChoicesPosition.add("Ведущий менеджер по работе с ключевыми клиентами");
        subChoicesPosition.add("Ведущий менеджер по работе с ключевыми партнерами");
        subChoicesPosition.add("Ведущий менеджер по работе с партнерами");
        subChoicesPosition.add("Ведущий менеджер 2 категории");
        subChoicesPosition.add("Ведущий программист");
        subChoicesPosition.add("Ведущий программист мобильных приложений");
        subChoicesPosition.add("Ведущий специалист");
        subChoicesPosition.add("Ведущий специалист разработки");
        subChoicesPosition.add("Ведущий экономист");
        subChoicesPosition.add("Ведущий экономист 2 категории");
        subChoicesPosition.add("Ведущий эксперт");
        subChoicesPosition.add("Ведущий эксперт по консалтингу");
        subChoicesPosition.add("Ведущий эксперт 1 категории");
        subChoicesPosition.add("Ведущий эксперт 2 категории");
        subChoicesPosition.add("Ведущий эксперт 3 категории");
        subChoicesPosition.add("Ведущий эксперт 4 категории");
        subChoicesPosition.add("Ведущий эксперт-консультант");
        subChoicesPosition.add("Ведущий юрист");
        subChoicesPosition.add("Водитель");
        subChoicesPosition.add("Водитель 1 категории");
        subChoicesPosition.add("Водитель-экспедитор");
        subChoicesPosition.add("Генеральный директор");
        subChoicesPosition.add("Главный IOS-программист");
        subChoicesPosition.add("Главный аналитик");
        subChoicesPosition.add("Главный архитектор");
        subChoicesPosition.add("Главный бухгалтер");
        subChoicesPosition.add("Главный инженер");
        subChoicesPosition.add("Главный программист");
        subChoicesPosition.add("Главный системный администратор");
        subChoicesPosition.add("Дежурный администратор");
        subChoicesPosition.add("Директор бизнес консалтинга");
        subChoicesPosition.add("Директор департамента");
        subChoicesPosition.add("Директор дирекции");
        subChoicesPosition.add("Директор единой службы качества");
        subChoicesPosition.add("Директор Комплаенс");
        subChoicesPosition.add("Директор лаборатории");
        subChoicesPosition.add("Директор отделения");
        subChoicesPosition.add("Директор по исследовательским проектам");
        subChoicesPosition.add("Директор по научной работе и инновациям");
        subChoicesPosition.add("Директор по обучению");
        subChoicesPosition.add("Директор по продвижению продуктов и решений");
        subChoicesPosition.add("Директор по работе с клиентами");
        subChoicesPosition.add("Директор по работе с ключевыми заказчиками");
        subChoicesPosition.add("Директор по работе с ключевыми партнерами");
        subChoicesPosition.add("Директор по развитию бизнеса");
        subChoicesPosition.add("Директор по технологиям");
        subChoicesPosition.add("Директор по технологиям разработки программного обеспечения");
        subChoicesPosition.add("Директор проектного офиса");
        subChoicesPosition.add("Директор центра");
        subChoicesPosition.add("Директор юридического департамента");
        subChoicesPosition.add("Заместитель генерального директора по организационно-коммерческим вопросам");
        subChoicesPosition.add("Заместитель директора департамента");
        subChoicesPosition.add("Заместитель Генерального директора");
        subChoicesPosition.add("Заместитель Генерального директора по проектной деятельности");
        subChoicesPosition.add("Заместитель генерального директора по работе с Госсектором");
        subChoicesPosition.add("Заместитель главного бухгалтера");
        subChoicesPosition.add("Заместитель директора дирекции");
        subChoicesPosition.add("Заместитель директора дирекции по административным вопросам");
        subChoicesPosition.add("Заместитель директора отделения");
        subChoicesPosition.add("Заместитель директора отделения по продвижению продуктов и решений спортивного направления");
        subChoicesPosition.add("Заместитель начальника отдела");
        subChoicesPosition.add("Заместитель руководителя департамента");
        subChoicesPosition.add("Заместитель финансового директора");
        subChoicesPosition.add("Инженер");
        subChoicesPosition.add("Инженер 1 категории");
        subChoicesPosition.add("И.О.начальника отдела");
        subChoicesPosition.add("Коммерческий директор");
        subChoicesPosition.add("Консультант");
        subChoicesPosition.add("Консультант-аналитик");
        subChoicesPosition.add("Консультант-эксперт");
        subChoicesPosition.add("Координатор ИТ-проектов");
        subChoicesPosition.add("Координатор проектов");
        subChoicesPosition.add("Координатор проектов по технологическому консалтингу");
        subChoicesPosition.add("Кредитный менеджер");
        subChoicesPosition.add("Курьер");
        subChoicesPosition.add("Менеджер");
        subChoicesPosition.add("Менеджер по логистике");
        subChoicesPosition.add("Менеджер по маркетингу");
        subChoicesPosition.add("Менеджер по партнерским программам");
        subChoicesPosition.add("Менеджер по персоналу");
        subChoicesPosition.add("Менеджер по продажам");
        subChoicesPosition.add("Менеджер по продукту");
        subChoicesPosition.add("Менеджер по работе с персоналом");
        subChoicesPosition.add("Менеджер по сопровождению корпоративных сайтов");
        subChoicesPosition.add("Менеджер продуктов");
        subChoicesPosition.add("Менеджер проектов в телекоммуникационном секторе");
        subChoicesPosition.add("Младший администратор проектов");
        subChoicesPosition.add("Младший аналитик");
        subChoicesPosition.add("Младший ассистент");
        subChoicesPosition.add("Младший инженер");
        subChoicesPosition.add("Младший менеджер");
        subChoicesPosition.add("Младший менеджер по логистике");
        subChoicesPosition.add("Младший специалист");
        subChoicesPosition.add("Младший эксперт");
        subChoicesPosition.add("Младший юрист");
        subChoicesPosition.add("Начальник отдела");
        subChoicesPosition.add("Начальник службы");
        subChoicesPosition.add("Первый зам.генерального директора");
        subChoicesPosition.add("Переводчик");
        subChoicesPosition.add("Помощник бухгалтера");
        subChoicesPosition.add("Помощник Генерального директора по выполнению функций режимно-секретного подразделения");
        subChoicesPosition.add("Помощник менеджера");
        subChoicesPosition.add("Помощник первого заместителя Генерального директора");
        subChoicesPosition.add("Помощник руководителя");
        subChoicesPosition.add("Помощник руководителя департамента");
        subChoicesPosition.add("Помощник финансового менеджера");
        subChoicesPosition.add("Референт");
        subChoicesPosition.add("Референт Генерального директора");
        subChoicesPosition.add("Руководитель группы разработки");
        subChoicesPosition.add("Руководитель департамента");
        subChoicesPosition.add("Руководитель направления");
        subChoicesPosition.add("Руководитель направления мобильных решений");
        subChoicesPosition.add("Руководитель направления проектов сопровождения");
        subChoicesPosition.add("Руководитель отдела");
        subChoicesPosition.add("Руководитель проекта");
        subChoicesPosition.add("Руководитель проектов");
        subChoicesPosition.add("Руководитель проектов внедрения");
        subChoicesPosition.add("Руководитель проектов разработки");
        subChoicesPosition.add("Руководитель секретариата");
        subChoicesPosition.add("Руководитель службы");
        subChoicesPosition.add("Руководитель финансовой группы");
        subChoicesPosition.add("Секретарь");
        subChoicesPosition.add("Системный администратор");
        subChoicesPosition.add("Системный архитектор");
        subChoicesPosition.add("Советник");
        subChoicesPosition.add("Советник генерального директора");
        subChoicesPosition.add("Советник Генерального директора по общим вопросам");
        subChoicesPosition.add("Советник заместителя генерального директора");
        subChoicesPosition.add("Советник первого заместителя Генерального директора");
        subChoicesPosition.add("Советник по выполнению функций РСО");
        subChoicesPosition.add("Советник по содействию бизнесу");
        subChoicesPosition.add("Специалист");
        subChoicesPosition.add("Специалист по комплексному ремонту и обслуживанию зданий");
        subChoicesPosition.add("Специалист 1 категории");
        subChoicesPosition.add("Стажер");
        subChoicesPosition.add("Старшая уборщица");
        subChoicesPosition.add("Старший администратор проектов");
        subChoicesPosition.add("Старший аналитик");
        subChoicesPosition.add("Старший архитектор проектов");
        subChoicesPosition.add("Старший ассистент по работе с вендорами");
        subChoicesPosition.add("Старший бизнес-аналитик");
        subChoicesPosition.add("Старший инженер");
        subChoicesPosition.add("Старший менеджер");
        subChoicesPosition.add("Старший менеджер по партнерским программам");
        subChoicesPosition.add("Старший менеджер по подбору и развитию персонала");
        subChoicesPosition.add("Старший менеджер по продажам");
        subChoicesPosition.add("Старший программист");
        subChoicesPosition.add("Старший секретарь");
        subChoicesPosition.add("Старший специалист");
        subChoicesPosition.add("Старший технический эксперт");
        subChoicesPosition.add("Старший экономист");
        subChoicesPosition.add("Старший эксперт");
        subChoicesPosition.add("Старший эксперт 1 категории");
        subChoicesPosition.add("Технический директор");
        subChoicesPosition.add("Технический писатель");
        subChoicesPosition.add("Технический эксперт");
        subChoicesPosition.add("Уборщица");
        subChoicesPosition.add("Управляющий офисным зданием");
        subChoicesPosition.add("Финансовый менеджер");
        subChoicesPosition.add("Экономист");
        subChoicesPosition.add("Эксперт");
        subChoicesPosition.add("Эксперт – консультант");
        subChoicesPosition.add("Эксперт по качеству");
        subChoicesPosition.add("Эксперт по производственной эстетике");
        subChoicesPosition.add("Юрист");

        return subChoicesPosition;
    }

    public List returnBranch() {
        List<String> subChoicesBranch = new ArrayList<String>();
        subChoicesBranch.add("ООО «Ай-ФОРС»");
        subChoicesBranch.add("ООО «ОССО»");
        subChoicesBranch.add("ООО «ФОРС – Карточные технологии»");
        subChoicesBranch.add("ООО «ФОРС Дистрибуция»");
        subChoicesBranch.add("ООО «ФОРС Телеком»");
        subChoicesBranch.add("ООО «ФОРС – Центр разработки»");

        return subChoicesBranch;
    }

    public List returnAdress() {
        List<String> subChoicesAdress = new ArrayList<String>();
        subChoicesAdress.add("Графский пер., 14");
        subChoicesAdress.add("Трифоновский тупик, 3");

        return subChoicesAdress;
    }
}
